/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import bd.GestionBD;
import java.io.File;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import modelos.Producto;
import modelos.Productos;
import modelos.Usuario;
import modelos.Usuarios;
import modelos.Venta;
import modelos.Ventas;

/**
 *
 * @author rbare
 */
public class Backend extends javax.swing.JFrame {
    
    //Objeto clase GestionBD para conectarnos a la BD
    GestionBD conexion;
    //Listado de productos, usuarios y ventas
    Productos listadoProductos;
    Usuarios listadoUsuarios;
    Ventas listadoVentas;
    //Modelo JListProductos
    DefaultListModel modeloJListUsuarios;
    DefaultListModel modeloJListProductos;
    DefaultListModel modeloJListVentas;
        
    
    /**
     * Creates new form EmpresaGUI
     */
    public Backend() {
        //Inicializamos los datos de Modelos
        this.modeloJListUsuarios = new DefaultListModel();
        this.modeloJListProductos = new DefaultListModel();
        this.modeloJListVentas = new DefaultListModel();
        
        //Inicializamos el listado de departamentos
        this.listadoProductos = new Productos();
        this.listadoUsuarios = new Usuarios();
        this.listadoVentas = new Ventas();
        
        //Instanciamos la conexion
        conexion = new GestionBD("localhost", "root", "", "empresa");
        listadoProductos = conexion.listarProductos();
        listadoUsuarios = conexion.listarUsuarios();
        listadoVentas = conexion.listarVentas();
        
        cargarProductos();
        cargarUsuarios();
        cargarVentas();
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        TabUsuarios = new javax.swing.JPanel();
        PanelListadoUsuarios = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListUsuario = new javax.swing.JList<>();
        PanelDetalleUsuario = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtnickUsuario = new javax.swing.JTextField();
        btnGuardarUsuario = new javax.swing.JButton();
        btnNuevoUsuario = new javax.swing.JButton();
        btnBorrarUsuario = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtapellidosUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtnombreUsuario = new javax.swing.JTextField();
        txtpasswordUsuario = new javax.swing.JTextField();
        jRadioButtonAdmin = new javax.swing.JRadioButton();
        jRadioButtonGerente = new javax.swing.JRadioButton();
        TabProductos = new javax.swing.JPanel();
        PanelListadoProductos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListProductos = new javax.swing.JList<>();
        PanelDetalleProductos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtidProducto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnombreProducto = new javax.swing.JTextField();
        btnGuardarProducto = new javax.swing.JButton();
        btnNuevoProducto = new javax.swing.JButton();
        btnBorrarProducto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSpinnerStockProducto = new javax.swing.JSpinner();
        jSpinnerPrecioProducto = new javax.swing.JSpinner();
        PanelGuardar = new javax.swing.JPanel();
        BotonGuardarImagenProducto = new javax.swing.JButton();
        txtRutaFichero = new javax.swing.JTextField();
        AbrirRuta = new javax.swing.JButton();
        TabVentas = new javax.swing.JPanel();
        PanelListadoUsuarios1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListVentas = new javax.swing.JList<>();
        btnBorrarVenta = new javax.swing.JButton();

        PanelListadoUsuarios.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado:"));

        jListUsuario.setModel(this.modeloJListUsuarios);
        jListUsuario.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListUsuarioValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListUsuario);

        javax.swing.GroupLayout PanelListadoUsuariosLayout = new javax.swing.GroupLayout(PanelListadoUsuarios);
        PanelListadoUsuarios.setLayout(PanelListadoUsuariosLayout);
        PanelListadoUsuariosLayout.setHorizontalGroup(
            PanelListadoUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelListadoUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelListadoUsuariosLayout.setVerticalGroup(
            PanelListadoUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListadoUsuariosLayout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        PanelDetalleUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuarios:"));

        jLabel4.setText("Nickname:");

        btnGuardarUsuario.setText("Guardar");
        btnGuardarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarUsuarioActionPerformed(evt);
            }
        });

        btnNuevoUsuario.setText("Nuevo");
        btnNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoUsuarioActionPerformed(evt);
            }
        });

        btnBorrarUsuario.setText("Borrar");
        btnBorrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarUsuarioActionPerformed(evt);
            }
        });

        jLabel5.setText("Apellidos:");

        jLabel6.setText("Contraseña:");

        jLabel7.setText("Rol:");

        jLabel10.setText("Nombre:");

        jRadioButtonAdmin.setText("Administrador");

        jRadioButtonGerente.setSelected(true);
        jRadioButtonGerente.setText("Gerente/Vendedor");

        javax.swing.GroupLayout PanelDetalleUsuarioLayout = new javax.swing.GroupLayout(PanelDetalleUsuario);
        PanelDetalleUsuario.setLayout(PanelDetalleUsuarioLayout);
        PanelDetalleUsuarioLayout.setHorizontalGroup(
            PanelDetalleUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDetalleUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDetalleUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDetalleUsuarioLayout.createSequentialGroup()
                        .addGroup(PanelDetalleUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtapellidosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpasswordUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDetalleUsuarioLayout.createSequentialGroup()
                        .addGroup(PanelDetalleUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelDetalleUsuarioLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnBorrarUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNuevoUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGuardarUsuario))
                            .addGroup(PanelDetalleUsuarioLayout.createSequentialGroup()
                                .addGroup(PanelDetalleUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnickUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                                .addGroup(PanelDetalleUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButtonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButtonGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(41, 41, 41))))
        );
        PanelDetalleUsuarioLayout.setVerticalGroup(
            PanelDetalleUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDetalleUsuarioLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PanelDetalleUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDetalleUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(9, 9, 9)
                        .addComponent(txtnickUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(PanelDetalleUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(txtnombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtapellidosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtpasswordUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addGroup(PanelDetalleUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarUsuario)
                    .addComponent(btnNuevoUsuario)
                    .addComponent(btnBorrarUsuario))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout TabUsuariosLayout = new javax.swing.GroupLayout(TabUsuarios);
        TabUsuarios.setLayout(TabUsuariosLayout);
        TabUsuariosLayout.setHorizontalGroup(
            TabUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabUsuariosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelListadoUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDetalleUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TabUsuariosLayout.setVerticalGroup(
            TabUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TabUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelDetalleUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelListadoUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Usuarios", TabUsuarios);

        PanelListadoProductos.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado:"));

        jListProductos.setModel(this.modeloJListProductos);
        jListProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListProductosMouseClicked(evt);
            }
        });
        jListProductos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListProductosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListProductos);

        javax.swing.GroupLayout PanelListadoProductosLayout = new javax.swing.GroupLayout(PanelListadoProductos);
        PanelListadoProductos.setLayout(PanelListadoProductosLayout);
        PanelListadoProductosLayout.setHorizontalGroup(
            PanelListadoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListadoProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelListadoProductosLayout.setVerticalGroup(
            PanelListadoProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListadoProductosLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelDetalleProductos.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos"));

        jLabel1.setText("ID:");

        txtidProducto.setEnabled(false);
        txtidProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidProductoActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        txtnombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreProductoActionPerformed(evt);
            }
        });

        btnGuardarProducto.setText("Guardar");
        btnGuardarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProductoActionPerformed(evt);
            }
        });

        btnNuevoProducto.setText("Nuevo");
        btnNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProductoActionPerformed(evt);
            }
        });

        btnBorrarProducto.setText("Borrar");
        btnBorrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarProductoActionPerformed(evt);
            }
        });

        jLabel3.setText("Precio:");

        jLabel8.setText("Stock:");
        jLabel8.setToolTipText("");

        jSpinnerStockProducto.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnerStockProducto.setToolTipText("");

        jSpinnerPrecioProducto.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));
        jSpinnerPrecioProducto.setToolTipText("");

        PanelGuardar.setBorder(javax.swing.BorderFactory.createTitledBorder("Subir imagen"));

        BotonGuardarImagenProducto.setText("Guardar imagen");
        BotonGuardarImagenProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarImagenProductoActionPerformed(evt);
            }
        });

        txtRutaFichero.setBorder(javax.swing.BorderFactory.createTitledBorder("Ruta:"));

        AbrirRuta.setText("Abrir");
        AbrirRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirRutaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelGuardarLayout = new javax.swing.GroupLayout(PanelGuardar);
        PanelGuardar.setLayout(PanelGuardarLayout);
        PanelGuardarLayout.setHorizontalGroup(
            PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGuardarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtRutaFichero, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AbrirRuta)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGuardarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonGuardarImagenProducto)
                .addGap(143, 143, 143))
        );
        PanelGuardarLayout.setVerticalGroup(
            PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGuardarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRutaFichero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AbrirRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(BotonGuardarImagenProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PanelDetalleProductosLayout = new javax.swing.GroupLayout(PanelDetalleProductos);
        PanelDetalleProductos.setLayout(PanelDetalleProductosLayout);
        PanelDetalleProductosLayout.setHorizontalGroup(
            PanelDetalleProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDetalleProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDetalleProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerStockProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDetalleProductosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBorrarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNuevoProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardarProducto)
                .addGap(41, 41, 41))
        );
        PanelDetalleProductosLayout.setVerticalGroup(
            PanelDetalleProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDetalleProductosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtidProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerStockProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelDetalleProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarProducto)
                    .addComponent(btnNuevoProducto)
                    .addComponent(btnBorrarProducto))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout TabProductosLayout = new javax.swing.GroupLayout(TabProductos);
        TabProductos.setLayout(TabProductosLayout);
        TabProductosLayout.setHorizontalGroup(
            TabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelListadoProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDetalleProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TabProductosLayout.setVerticalGroup(
            TabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelListadoProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelDetalleProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Productos", TabProductos);

        PanelListadoUsuarios1.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado:"));

        jListVentas.setModel(this.modeloJListVentas);
        jListVentas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListVentasValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jListVentas);

        javax.swing.GroupLayout PanelListadoUsuarios1Layout = new javax.swing.GroupLayout(PanelListadoUsuarios1);
        PanelListadoUsuarios1.setLayout(PanelListadoUsuarios1Layout);
        PanelListadoUsuarios1Layout.setHorizontalGroup(
            PanelListadoUsuarios1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListadoUsuarios1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelListadoUsuarios1Layout.setVerticalGroup(
            PanelListadoUsuarios1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelListadoUsuarios1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnBorrarVenta.setText("Borrar Venta");
        btnBorrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TabVentasLayout = new javax.swing.GroupLayout(TabVentas);
        TabVentas.setLayout(TabVentasLayout);
        TabVentasLayout.setHorizontalGroup(
            TabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabVentasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelListadoUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(TabVentasLayout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(btnBorrarVenta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TabVentasLayout.setVerticalGroup(
            TabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelListadoUsuarios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBorrarVenta)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ventas", TabVentas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidProductoActionPerformed
        
    }//GEN-LAST:event_txtidProductoActionPerformed

    private void jListProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListProductosMouseClicked
        
    }//GEN-LAST:event_jListProductosMouseClicked

    private void jListUsuarioValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListUsuarioValueChanged
        mostrarUsuarios(this.jListUsuario.getSelectedIndex());
    }//GEN-LAST:event_jListUsuarioValueChanged

    private void jListProductosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListProductosValueChanged
        mostrarProducto(this.jListProductos.getSelectedIndex());
    }//GEN-LAST:event_jListProductosValueChanged

    private void btnNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProductoActionPerformed
        limpiarFormularioProducto();
    }//GEN-LAST:event_btnNuevoProductoActionPerformed

    private void btnGuardarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProductoActionPerformed
        Producto producto = new Producto();
        if (!this.txtidProducto.getText().isEmpty()) {
            producto.setId_producto(Integer.parseInt(this.txtidProducto.getText()));
        
        }
        producto.setNombre(this.txtnombreProducto.getText());
        guardarProducto(producto);
    }//GEN-LAST:event_btnGuardarProductoActionPerformed

    private void btnBorrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarProductoActionPerformed
        Producto producto = new Producto();
        if (!this.txtidProducto.getText().isBlank()) {
            producto.setId_producto(Integer.parseInt(this.txtidProducto.getText()));
        
        }
        producto.setNombre(this.txtnombreProducto.getText());
        borrarProducto(producto);
    }//GEN-LAST:event_btnBorrarProductoActionPerformed

    private void btnNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoUsuarioActionPerformed
        limpiarFormularioUsuario();
    }//GEN-LAST:event_btnNuevoUsuarioActionPerformed

    private void btnGuardarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarUsuarioActionPerformed
        Usuario usuario = new Usuario();
        if (!this.txtnickUsuario.getText().isBlank()) {
            usuario.setNickname(this.txtnickUsuario.getText());
        
        }
        usuario.setNombre(this.txtnombreUsuario.getText());
        usuario.setApellidos(this.txtapellidosUsuario.getText());
        usuario.setPassword(Integer.parseInt(this.txtpasswordUsuario.getText()));
        if (this.jRadioButtonAdmin.isSelected()) {
            usuario.setRol(0);
        }else{
            usuario.setRol(1);
        }
        guardarUsuario(usuario);
    }//GEN-LAST:event_btnGuardarUsuarioActionPerformed

    private void btnBorrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarUsuarioActionPerformed
        Usuario usuario = new Usuario();
        if (!this.txtnickUsuario.getText().isBlank()) {
            usuario.setNickname(this.txtnickUsuario.getText());
        
        }
        borrarUsuario(usuario);
    }//GEN-LAST:event_btnBorrarUsuarioActionPerformed

    private void txtnombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreProductoActionPerformed

    private void BotonGuardarImagenProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarImagenProductoActionPerformed
        File fselect = new File(this.txtRutaFichero.getText());
        conexion.setFoto(Integer.parseInt(this.txtidProducto.getText()), fselect);
    }//GEN-LAST:event_BotonGuardarImagenProductoActionPerformed

    private void AbrirRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirRutaActionPerformed
        File fselect = new File(this.txtRutaFichero.getText());
        JFileChooser chooser = new JFileChooser();
        // optionally set chooser options ...
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            fselect = chooser.getSelectedFile();
            // read  and/or display the file somehow. ....
            this.txtRutaFichero.setText(fselect.getPath());
        } else {
            // user changed their mind
        }
    }//GEN-LAST:event_AbrirRutaActionPerformed

    private void jListVentasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListVentasValueChanged
        
    }//GEN-LAST:event_jListVentasValueChanged

    private void btnBorrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarVentaActionPerformed
        Venta venta = new Venta();
        venta.setId(this.jListVentas.getSelectedIndex());
        Venta venta_buscada = conexion.buscarVentaID(venta);
        borrarVenta(venta_buscada);
    }//GEN-LAST:event_btnBorrarVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Backend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Backend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Backend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Backend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbrirRuta;
    private javax.swing.JButton BotonGuardarImagenProducto;
    private javax.swing.JPanel PanelDetalleProductos;
    private javax.swing.JPanel PanelDetalleUsuario;
    private javax.swing.JPanel PanelGuardar;
    private javax.swing.JPanel PanelListadoProductos;
    private javax.swing.JPanel PanelListadoUsuarios;
    private javax.swing.JPanel PanelListadoUsuarios1;
    private javax.swing.JPanel TabProductos;
    private javax.swing.JPanel TabUsuarios;
    private javax.swing.JPanel TabVentas;
    private javax.swing.JButton btnBorrarProducto;
    private javax.swing.JButton btnBorrarUsuario;
    private javax.swing.JButton btnBorrarVenta;
    private javax.swing.JButton btnGuardarProducto;
    private javax.swing.JButton btnGuardarUsuario;
    private javax.swing.JButton btnNuevoProducto;
    private javax.swing.JButton btnNuevoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jListProductos;
    private javax.swing.JList<String> jListUsuario;
    private javax.swing.JList<String> jListVentas;
    private javax.swing.JRadioButton jRadioButtonAdmin;
    private javax.swing.JRadioButton jRadioButtonGerente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinnerPrecioProducto;
    private javax.swing.JSpinner jSpinnerStockProducto;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtRutaFichero;
    private javax.swing.JTextField txtapellidosUsuario;
    private javax.swing.JTextField txtidProducto;
    private javax.swing.JTextField txtnickUsuario;
    private javax.swing.JTextField txtnombreProducto;
    private javax.swing.JTextField txtnombreUsuario;
    private javax.swing.JTextField txtpasswordUsuario;
    // End of variables declaration//GEN-END:variables

    
//PRODUCTOS------------------------------------------------------------------------------
    private void cargarProductos() {
        //Limpiar el listado
        this.modeloJListProductos.clear();
        //Actualizar el listado
        this.listadoProductos = conexion.listarProductos();
        //Debemos coger el listado de productos y cargarlo en el modeloJListProductos
        for (int i = 0; i < this.listadoProductos.size(); i++) {
            //Añadimos cada porducto al jlist
            this.modeloJListProductos.addElement(this.listadoProductos.getProducto(SOMEBITS).getNombre());
            System.out.println(this.listadoProductos.getProducto(SOMEBITS).getNombre());
        }
        
    }
    
    private void mostrarProducto(int i){
        Producto productoSel = new Producto();
        productoSel = this.listadoProductos.getProducto(i);
        
        this.txtidProducto.setText(String.valueOf(productoSel.getId_producto()));
        this.txtnombreProducto.setText(productoSel.getNombre());
        this.jSpinnerPrecioProducto.setValue(productoSel.getPrecio());
        this.jSpinnerStockProducto.setValue(productoSel.getStock());
        
    }

    //Borra el contenido de los campos del detalle de Productos
    private void limpiarFormularioProducto() {
        this.txtidProducto.setText("");
        this.txtnombreProducto.setText("");
        this.jSpinnerPrecioProducto.setValue(0);
        this.jSpinnerStockProducto.setValue(0);
    }

    private void guardarProducto(Producto producto) {
        //Compruebo si es un producto nuevo o es una modificaion
        if (producto.getId_producto() == -1) {
            conexion.insertarProducto(producto);
            cargarProductos();
            this.jListProductos.setSelectedIndex(this.listadoProductos.size() - 1);
        }else{
            conexion.modificarProducto(producto);
            int posSel = this.jListProductos.getSelectedIndex();
            cargarProductos();
            this.jListProductos.setSelectedIndex(posSel);
        }
    }

    private void borrarProducto(Producto producto) {
        //Comprobar que el producto a borrar tenga un id valido
        if ( producto.getId_producto() > -1) {
            conexion.borrarProducto(producto);
            cargarProductos();
            this.jListProductos.setSelectedIndex(this.listadoProductos.size() - 1);
        }
        
    }
    
//USUARIOS------------------------------------------------------------------------------
    private void cargarUsuarios() {
        //Limpiar el listado
        this.modeloJListUsuarios.clear();
        //Actualizar el listado
        this.listadoUsuarios = conexion.listarUsuarios();
        //Debemos coger el listado de usuarios y cargarlo en el modeloJListUsuarios
        for (int i = 0; i < this.listadoUsuarios.size(); i++) {
            //Añadimos cada usuario al jlist
            this.modeloJListUsuarios.addElement(this.listadoUsuarios.getUsuario(i).getNombre());
            System.out.println(this.listadoUsuarios.getUsuario(i).getNombre());
        }
        
    }
    
    private void mostrarUsuarios(int i){
        if ( i >= 0) {
            Usuario usuarioSel = new Usuario();
            usuarioSel = this.listadoUsuarios.getUsuario(i);

            this.txtnickUsuario.setText(usuarioSel.getNickname());
            this.txtnombreUsuario.setText(usuarioSel.getNombre());
            this.txtapellidosUsuario.setText(usuarioSel.getApellidos());
            this.txtpasswordUsuario.setText(String.valueOf(usuarioSel.getPassword()));
            if (usuarioSel.getRol() == 0) {
                this.jRadioButtonAdmin.setSelected(true);
                this.jRadioButtonGerente.setSelected(false);
            }else{
                this.jRadioButtonAdmin.setSelected(false);
                this.jRadioButtonGerente.setSelected(true);
            }
            System.out.println(usuarioSel.getNombre());
        }
    }

    //Borra el contenido de los campos del detalle de Usuario
    private void limpiarFormularioUsuario() {
        this.txtnickUsuario.setText("");
        this.txtnombreUsuario.setText("");
        this.txtapellidosUsuario.setText("");
        this.txtpasswordUsuario.setText("");
        this.jRadioButtonAdmin.setSelected(false);
        this.jRadioButtonGerente.setSelected(true);
        
    }

    private void guardarUsuario(Usuario usuario) {
        //Compruebo si es un usuario nuevo o es una modificaion
        if (usuario.getNickname().isBlank()) {
            conexion.insertarUsuario(usuario);
            cargarUsuarios();
            this.jListUsuario.setSelectedIndex(this.listadoUsuarios.size() - 1);
        }else{
            conexion.modificarUsuario(usuario);
            int posSel = this.jListUsuario.getSelectedIndex();
            cargarUsuarios();
            this.jListUsuario.setSelectedIndex(posSel);
        }
    }

    private void borrarUsuario(Usuario usuario) {
        //Comprobar que el usuario a borrar tenga un nick valido
        if ( usuario.getNickname() != "") {
            conexion.borrarUsuario(usuario);
            cargarUsuarios();
            this.jListUsuario.setSelectedIndex(this.listadoUsuarios.size() - 1);
        }
        
    }
    
//VENTAS------------------------------------------------------------------------------
    private void cargarVentas() {
        //Limpiar el listado
        this.modeloJListVentas.clear();
        //Actualizar el listado
        this.listadoVentas = conexion.listarVentas();
        //Debemos coger el listado de ventas y cargarlo en el modeloListVentas
        for (int i = 0; i < this.listadoVentas.size(); i++) {
            //Añadimos cada venta al jlist
            this.modeloJListVentas.addElement(this.listadoVentas.getVenta(i));
            System.out.println(this.listadoVentas.getVenta(i));
        }
    }
    
    private void borrarVenta(Venta venta) {
        //Comprobar que la venta a borrar tenga un id valido
        if ( venta.getId() > -1) {
            conexion.borrarVenta(venta);
            cargarVentas();
            this.jListVentas.setSelectedIndex(this.listadoVentas.size() - 1);
        }
        
    }
    
}
